version: '3.4'

services:
  budgetapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "704:80"

  userapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

    ports:
      - "701:80"

  expenseapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "703:80"


  incomeapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

    ports:
      - "702:80"


  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "777:80"


  notification:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

    ports:
      - "707:80"

