version: '3.4'

networks:
  backend:

services:
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=duckie
      - RABBITMQ_DEFAULT_PASS=01
    restart: always
    networks:
      - backend

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    hostname: sqlserver
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Duckie@01"
    restart: always
    networks:
      - backend

  budgetapi:
    container_name: budgetapi
    image: ${DOCKER_REGISTRY-}budgetapi
    build:
      context: .
      dockerfile: BudgetAPI/Dockerfile
    networks:
      - backend
    depends_on:
        - sqlserver

  userapi:
    container_name: userapi
    image: ${DOCKER_REGISTRY-}userapi
    hostname: userapi
    build:
      context: .
      dockerfile: UserAPI/Dockerfile
    networks:
     - backend
    depends_on:
        - sqlserver


  expenseapi:
    container_name: expenseapi
    image: ${DOCKER_REGISTRY-}expenseapi
    build:
      context: .
      dockerfile: ExpenseAPI/Dockerfile
    networks:
    - backend
    depends_on:
        - sqlserver


  incomeapi:
    container_name: incomeapi
    image: ${DOCKER_REGISTRY-}incomeapi
    build:
      context: .
      dockerfile: IncomeAPI/Dockerfile
    environment:
     - connectionStrings=Server=sqlserver;Database=PFM_Income;User Id=sa;Password=Duckie@01;Encrypt=False;TrustServerCertificate=True
    networks:
      - backend
    depends_on:
        - sqlserver


  gateway:
    container_name: gateway
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    networks:
      - backend
    depends_on:
        - sqlserver



  notification:
    container_name: notification
    image: ${DOCKER_REGISTRY-}notification
    build:
      context: .
      dockerfile: Notification/Dockerfile
    networks:
        - backend   
    depends_on:
        - rabbitmq

